name: Greetings

on: [pull_request,issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to Open-Protocol,Thanks so much for creating your first issue :)'
        pr-message: 'Congrats you have created your first PR! Open-protocol is grateful to you :)'
