name: Greetings

on: [pull_request, issues]

jobs:
  greeting: Hello! Welcome to Open-protocol
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for adding an issue, we will get on it soon'
        pr-message: 'Congrats on your first pr!'
